import React, { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Download, FileDown, Loader2 } from 'lucide-react';
import jsPDF from 'jspdf';
import { autoTable } from 'jspdf-autotable';

export default function ExportControls({ data, columns, filename, propertyName, title }) {
  const [isGeneratingPdf, setIsGeneratingPdf] = useState(false);

  const handleExportCSV = () => {
    if (!data.length) return;
    const headers = columns.map(c => c.header).join(',');
    const rows = data.map(row =>
      columns.map(c => {
        const v = row[c.key];
        return typeof v === 'string' && v.includes(',') ? `"${v}"` : (v ?? '');
      }).join(',')
    );
    const csv = [headers, ...rows].join('\n');
    const blob = new Blob([csv], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${filename}.csv`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleExportPDF = async () => {
    if (!data.length) return;
    setIsGeneratingPdf(true);
    try {
      const doc = new jsPDF();

      // Brand header — navy background
      doc.setFillColor(16, 27, 41); // #101B29
      doc.rect(0, 0, 210, 25, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(16);
      doc.text(`UNIT — ${title}`, 14, 16);
      doc.setFontSize(10);
      doc.text(propertyName, 196, 16, { align: 'right' });

      // Accent bar
      doc.setFillColor(70, 90, 117); // #465A75
      doc.rect(0, 25, 210, 2, 'F');

      // Reset text color
      doc.setTextColor(0, 0, 0);

      // Table
      autoTable(doc, {
        startY: 32,
        head: [columns.map(c => c.header)],
        body: data.map(row => columns.map(c => {
          const v = row[c.key];
          if (c.key === 'amount' && typeof v === 'number') return `$${v.toLocaleString()}`;
          return v ?? '';
        })),
        headStyles: { fillColor: [29, 38, 58], textColor: [255, 255, 255] },
        alternateRowStyles: { fillColor: [248, 248, 248] },
        styles: { fontSize: 10 }
      });

      // Footer
      const pageCount = doc.internal.getNumberOfPages();
      for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        doc.text(
          `Generated by UNIT — ${new Date().toLocaleDateString()}`,
          105, doc.internal.pageSize.height - 10, { align: 'center' }
        );
      }

      doc.save(`${filename}.pdf`);
    } finally {
      setIsGeneratingPdf(false);
    }
  };

  return (
    <div className="flex items-center gap-2">
      <Button
        variant="outline"
        size="sm"
        onClick={handleExportCSV}
        disabled={!data.length}
      >
        <Download className="w-3.5 h-3.5 mr-1" />
        Export CSV
      </Button>
      <Button
        variant="outline"
        size="sm"
        onClick={handleExportPDF}
        disabled={!data.length || isGeneratingPdf}
      >
        {isGeneratingPdf ? (
          <Loader2 className="w-3.5 h-3.5 mr-1 animate-spin" />
        ) : (
          <FileDown className="w-3.5 h-3.5 mr-1" />
        )}
        Export PDF
      </Button>
    </div>
  );
}
